version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - sudo python -m pip install boto3
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      - python aaa.py
  post_build:
    commands:
      - echo Build completed on `date`
